# Generated by Django 5.2.7 on 2025-11-06 17:29

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classificationhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Classification History', 'verbose_name_plural': 'Classification Histories'},
        ),
        migrations.AddField(
            model_name='classificationhistory',
            name='classification_results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificationhistory',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificationhistory',
            name='file_path',
            field=models.CharField(blank=True, help_text='Stored file path', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='classificationhistory',
            name='file_size',
            field=models.IntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='classificationhistory',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificationhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='classificationhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='classificationhistory',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='classificationhistory',
            name='filename',
            field=models.CharField(help_text='Original filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='classificationhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='classificationhistory',
            index=models.Index(fields=['-created_at'], name='soal_classi_created_4ed500_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationhistory',
            index=models.Index(fields=['user', '-created_at'], name='soal_classi_user_id_0e1d15_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationhistory',
            index=models.Index(fields=['status'], name='soal_classi_status_3bd318_idx'),
        ),
    ]
