# Generated by Django 5.2.7 on 2025-11-03 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='File Name')),
                ('file', models.FileField(upload_to='uploads/questions/', verbose_name='Question File')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='uploads/results/', verbose_name='Result File')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Total Questions')),
                ('q1_count', models.IntegerField(default=0, verbose_name='C1 - Remember')),
                ('q2_count', models.IntegerField(default=0, verbose_name='C2 - Understand')),
                ('q3_count', models.IntegerField(default=0, verbose_name='C3 - Apply')),
                ('q4_count', models.IntegerField(default=0, verbose_name='C4 - Analyze')),
                ('q5_count', models.IntegerField(default=0, verbose_name='C5 - Evaluate')),
                ('q6_count', models.IntegerField(default=0, verbose_name='C6 - Create')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classifications',
                'db_table': 'classification',
                'ordering': ['-created_at'],
            },
        ),
    ]
