# Generated by Django 5.2.7 on 2025-11-08 07:55

import apps.klasifikasi.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klasifikasi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('category', models.CharField(choices=[('C1', 'C1: Remember'), ('C2', 'C2: Understand'), ('C3', 'C3: Apply'), ('C4', 'C4: Analyze'), ('C5', 'C5: Evaluate'), ('C6', 'C6: Create')], max_length=2)),
                ('confidence_score', models.FloatField(default=0.0, help_text='ML model confidence score (0-1)')),
                ('choice_a', models.TextField(blank=True, null=True)),
                ('choice_b', models.TextField(blank=True, null=True)),
                ('choice_c', models.TextField(blank=True, null=True)),
                ('choice_d', models.TextField(blank=True, null=True)),
                ('choice_e', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['question_number'],
            },
        ),
        migrations.RemoveField(
            model_name='classification',
            name='notes',
        ),
        migrations.AddField(
            model_name='classification',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='file_size',
            field=models.IntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='classification',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='file',
            field=models.FileField(help_text='Upload PDF, DOC, or DOCX file', upload_to=apps.klasifikasi.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='classification',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='classification',
            name='q1_count',
            field=models.IntegerField(default=0, verbose_name='C1: Remember'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='q2_count',
            field=models.IntegerField(default=0, verbose_name='C2: Understand'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='q3_count',
            field=models.IntegerField(default=0, verbose_name='C3: Apply'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='q4_count',
            field=models.IntegerField(default=0, verbose_name='C4: Analyze'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='q5_count',
            field=models.IntegerField(default=0, verbose_name='C5: Evaluate'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='q6_count',
            field=models.IntegerField(default=0, verbose_name='C6: Create'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='result_file',
            field=models.FileField(blank=True, help_text='Generated report file', null=True, upload_to=apps.klasifikasi.models.result_directory_path),
        ),
        migrations.AlterField(
            model_name='classification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='classification',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['-created_at'], name='klasifikasi_created_8f4370_idx'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['user', '-created_at'], name='klasifikasi_user_id_2a5a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['status'], name='klasifikasi_status_05978b_idx'),
        ),
        migrations.AlterModelTable(
            name='classification',
            table=None,
        ),
        migrations.AddField(
            model_name='question',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='klasifikasi.classification'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['classification', 'question_number'], name='klasifikasi_classif_a4bd85_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category'], name='klasifikasi_categor_4d2368_idx'),
        ),
    ]
