# Generated by Django 5.2.7 on 2025-11-09 15:16

import apps.klasifikasi.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klasifikasi', '0002_question_remove_classification_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='classification',
            name='klasifikasi_status_05978b_idx',
        ),
        migrations.RenameField(
            model_name='classification',
            old_name='processed_at',
            new_name='processing_completed_at',
        ),
        migrations.AddField(
            model_name='classification',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA256 hash of file for duplicate detection', max_length=64),
        ),
        migrations.AddField(
            model_name='classification',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='processing_time_seconds',
            field=models.IntegerField(blank=True, help_text='Time taken to process in seconds', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='question',
            name='is_manually_classified',
            field=models.BooleanField(default=False, help_text='Whether this question was manually reclassified'),
        ),
        migrations.AddField(
            model_name='question',
            name='previous_category',
            field=models.CharField(blank=True, help_text='Previous category before manual reclassification', max_length=2),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classification',
            name='file',
            field=models.FileField(help_text='Upload PDF, DOC, or DOCX file (max 10MB)', upload_to=apps.klasifikasi.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), apps.klasifikasi.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='classification',
            name='file_size',
            field=models.IntegerField(default=0, help_text='File size in bytes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='classification',
            name='filename',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='classification',
            name='q1_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='C1: Remember'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='q2_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='C2: Understand'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='q3_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='C3: Apply'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='q4_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='C4: Analyze'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='q5_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='C5: Evaluate'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='q6_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='C6: Create'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='classification',
            name='total_questions',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('C1', 'C1: Remember'), ('C2', 'C2: Understand'), ('C3', 'C3: Apply'), ('C4', 'C4: Analyze'), ('C5', 'C5: Evaluate'), ('C6', 'C6: Create')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_a',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_b',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_c',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_d',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_e',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='ML model confidence score (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('classification', 'question_number')},
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['status', '-created_at'], name='klasifikasi_status_10cef1_idx'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['file_hash'], name='klasifikasi_file_ha_07b93d_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['confidence_score'], name='klasifikasi_confide_044724_idx'),
        ),
        migrations.AddConstraint(
            model_name='classification',
            constraint=models.CheckConstraint(condition=models.Q(('total_questions__gte', 0)), name='total_questions_non_negative'),
        ),
    ]
