# Generated by Django 5.2.7 on 2025-11-09 16:43

import apps.klasifikasi.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klasifikasi', '0003_remove_classification_klasifikasi_status_05978b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='task_id',
            field=models.CharField(blank=True, default='', help_text='Celery task ID for tracking', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes about this question'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this classification was created'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Error message if processing failed'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='file',
            field=models.FileField(help_text='Upload PDF, DOC, or DOCX file (max 10MB)', upload_to=apps.klasifikasi.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), apps.klasifikasi.models.validate_file_size, apps.klasifikasi.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='classification',
            name='filename',
            field=models.CharField(db_index=True, help_text='Original filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='classification',
            name='processing_completed_at',
            field=models.DateTimeField(blank=True, help_text='When processing completed', null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, help_text='When processing started', null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='processing_time_seconds',
            field=models.IntegerField(blank=True, help_text='Time taken to process in seconds', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='classification',
            name='q1_count',
            field=models.IntegerField(default=0, help_text='Number of C1 level questions', validators=[django.core.validators.MinValueValidator(0)], verbose_name='C1: Remember'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='q2_count',
            field=models.IntegerField(default=0, help_text='Number of C2 level questions', validators=[django.core.validators.MinValueValidator(0)], verbose_name='C2: Understand'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='q3_count',
            field=models.IntegerField(default=0, help_text='Number of C3 level questions', validators=[django.core.validators.MinValueValidator(0)], verbose_name='C3: Apply'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='q4_count',
            field=models.IntegerField(default=0, help_text='Number of C4 level questions', validators=[django.core.validators.MinValueValidator(0)], verbose_name='C4: Analyze'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='q5_count',
            field=models.IntegerField(default=0, help_text='Number of C5 level questions', validators=[django.core.validators.MinValueValidator(0)], verbose_name='C5: Evaluate'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='q6_count',
            field=models.IntegerField(default=0, help_text='Number of C6 level questions', validators=[django.core.validators.MinValueValidator(0)], verbose_name='C6: Create'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='result_file',
            field=models.FileField(blank=True, help_text='Generated report file (PDF)', null=True, upload_to=apps.klasifikasi.models.result_directory_path),
        ),
        migrations.AlterField(
            model_name='classification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current processing status', max_length=20),
        ),
        migrations.AlterField(
            model_name='classification',
            name='total_questions',
            field=models.IntegerField(default=0, help_text='Total number of questions classified', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='classification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this classification was last updated'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='user',
            field=models.ForeignKey(help_text='User who owns this classification', on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('C1', 'C1: Remember'), ('C2', 'C2: Understand'), ('C3', 'C3: Apply'), ('C4', 'C4: Analyze'), ('C5', 'C5: Evaluate'), ('C6', 'C6: Create')], db_index=True, help_text="Bloom's Taxonomy category", max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_a',
            field=models.TextField(blank=True, default='', help_text='Choice A'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_b',
            field=models.TextField(blank=True, default='', help_text='Choice B'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_c',
            field=models.TextField(blank=True, default='', help_text='Choice C'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_d',
            field=models.TextField(blank=True, default='', help_text='Choice D'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_e',
            field=models.TextField(blank=True, default='', help_text='Choice E'),
        ),
        migrations.AlterField(
            model_name='question',
            name='classification',
            field=models.ForeignKey(help_text='Classification this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='klasifikasi.classification'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', help_text='Correct answer choice', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_manually_classified',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this question was manually reclassified'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(help_text='Question number in the original document', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(help_text='The actual question text'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_manually_classified'], name='klasifikasi_is_manu_c53be7_idx'),
        ),
    ]
