# Generated by Django 5.2.7 on 2025-11-08 10:54

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_options_alter_user_options_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, help_text='Profile picture (max 2MB, JPG/PNG)', null=True, upload_to=apps.users.models.user_profile_image_path),
        ),
    ]
