# Generated by Django 5.2.7 on 2025-11-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='notif_classification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notif_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='notif_tips',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notif_updates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='results_per_page',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_tutorials',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='Asia/Jakarta', max_length=50),
        ),
    ]
